version: '3'
services:
  node1:
    container_name: ming-node1
    build:
      context: ./node1
    ports:
      - "3001:3000"
    networks:
      - ming-network
    environment:
      - NODE_ID=node1

  node2:
    container_name: ming-node2
    build:
      context: ./node2
    ports:
      - "3002:3000"
    networks:
      - ming-network
    environment:
      - NODE_ID=node2

  node3:
    container_name: ming-node3
    build:
      context: ./node3
    ports:
      - "3003:3000"
    networks:
      - ming-network
    environment:
      - NODE_ID=node3

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - uptime-kuma-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:3001  # <Host Port>:<Container Port>
    restart: always

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Exposing Docker socket
      - portainer_data:/data
    ports:
      - 9000:9000  # Expose Portainer on port 9000
    networks:
      - ming-network
    restart: always

volumes:
  uptime-kuma-data:
  portainer_data:

networks:
  ming-network:
    driver: bridge
